package src.main.java.clas;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'georgie' at '9/12/15 6:09 PM' with Gradle 2.6
 *
 * @author georgie, @date 9/12/15 6:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
